### ISSUE TITLE
Code for default behaviour of implicit-only program options hardly readable

### ISSUE THREAD

**Issue by jsche** [Inovesa/Inovesa#20]
introduced in: https://github.com/Inovesa/Inovesa/commit/6c136b65c9a64d3c12fc2e7323f03ceefe8122d9

Program options `--gui, --SavePhaseSpace, --SaveSourceMap, --verbose` don't have a default value.

**Comment by p-snft** [comment]
Are you sure? There are defaults defined in _programopts_file, but _programopts_cli has implicit true regardless of the default.

**Comment by jsche** [comment]
According to the [docs](http://www.boost.org/doc/libs/1_65_0/doc/html/boost/program_options/typed_value.html#idp709203296-bb), the function of implicit_value() is
> Specifies an implicit value, which will be used if the option is given, but without an adjacent value.

The default behaviour is not specified and random.

**Comment by p-snft** [comment]
The default values are defined [somewhere else](https://github.com/Inovesa/Inovesa/blob/6c136b65c9a64d3c12fc2e7323f03ceefe8122d9/src/IO/ProgramOptions.cpp#L108). I renamed the ticket and accepted you patch, thanks.
