### ISSUE TITLE
inovesa bunch length / energy spread is variance instead of standard deviation

### ISSUE THREAD

**Issue by t-bz** [Inovesa/Inovesa#24]
Inovesa writes the variance as bunch length / energy spread to hdf5 instead of the standard deviation.
[See line, e.g. bunch length.](https://github.com/Inovesa/Inovesa/blob/a87ccdbf12055f1d8e26217d9c429a9a32034c02/src/IO/HDF5File.cpp#L802)

**Comment by p-snft** [comment]
Ouch! Thanks a lot.

**Comment by jsche** [comment]
That's the standard deviation, but from `getBunchLength()` I'd expect `2*std::sqrt(getMoment(0,1));`.

**Comment by p-snft** [comment]
The (RMS) bunch length is defined to be one standard deviation. So now, the behavior is as one would expect it.

**Comment by jsche** [comment]
You're right, it's the common definition.
