### ISSUE TITLE
Damping and diffusion in pseudo-particle tracking

### ISSUE THREAD

**Issue by t-bz** [Inovesa/Inovesa#53]
At present, pseudo-particle tracking in Inovesa should only be used for short timescales as the present consideration of damping and diffusion results in a disproportionate tendency of single particles to spiral inwards (toward the synchronous particle).
Theoretically, there should be a way (possibly stochastic) to circumvent this effect.

**Comment by p-snft** [comment]
The stochastic single-particle motion is described in [IPAC2018-THPAK032](http://ipac2018.vrws.de/papers/thpak032.pdf). It should be rather easy to include it to FokkerPlanckMap::applyTo(...).
