### ISSUE TITLE
Load and store particle positions in units of the associated axes

### ISSUE THREAD

**Issue by t-bz** [Inovesa/Inovesa#55]
If pseudo-particle tracking is used, particle positions are currently given in grid coordinates (regarding both, initial positions given as txt-file as well as stored positions in the hdf5-file). In order to increase usability and consistency, particle positions should be given in units of the associated axes.

**Comment by p-snft** [comment]
Implemented in branch leading to v1.1. Closing this issue to keep track of what is still to do.
