### ISSUE TITLE
Use SPDX license identifier?

### ISSUE THREAD

**Issue by p-snft** [Inovesa/Inovesa#66]
Currently, every file should contain a verbose text describing the license. (This can be considered 90s' style.) Today, often SPDX license identifiers are used. Possibilities include:

a) The way some Linux files do it.

    /* SPDX-License-Identifier: GPL-2.0 WITH Linux-syscall-note */

b) Adding the identifier and radically shortening the current license information while still keeping it human readable. (Linux is well known and might not need additional hints.)

    // SPDX-License-Identifier: GPL-3.0-or-later
    /*
     * This file is part of Inovesa (github.com/Inovesa/Inovesa).
     * It's copyrighted by the contributors recorded in the version control history of the file.
     */

c) Or, to allow non-git contributions with explicit naming of the copyright owners. In this second case, authors are responsible to add a line for their name when sending in patches. Also, the list can become quite messy.

    /******************************************************************************
     * This file is part of Inovesa (github.com/Inovesa/Inovesa).                 *
     * Copyright (c) 2014-2018: Patrik Schönfeldt                                 *
     *                                                                            *
     * SPDX-License-Identifier: GPL-3.0-or-later                                  *
     ******************************************************************************/

d) Alternatively, one might just add the identifier in front of the current header. (This at least helps identifying the conditions by simple crawlers.)

    // SPDX-License-Identifier: GPL-3.0-or-later

**Comment by p-snft** [comment]
I came up with this idea because the identifiers helped me a lot while browsing for code I could use in another project. I would opt for the option b).

**Comment by t-bz** [comment]
I like the idea and also think option b) is the best choice.

**Comment by p-snft** [comment]
I just was informed that the FSFE discourages to rely on the version control system to track the copyright owners. However, there is a further option, which is to collect the contributors in a CONTRIBUTORS file and to point to this one. We already have such a file, so tis should be no problem.
